# Generated by Django 3.0.6 on 2020-05-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200520_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
    ]
