# Generated by Django 3.0.6 on 2020-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200520_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='Имя автора'),
        ),
    ]
